In [2]:
def short_function(x):
    return x *2

equiv_anon = lambda x: x*2
print(equiv_anon(2))
print(short_function(2))


def apply_to_list(some_list, f):
    return[f(x) for x in some_list]
ints = [4,0,1,5,6]

computed = apply_to_list(ints, lambda x: x**2)
print(computed)

4
4
[16, 0, 1, 25, 36]


In [4]:
some_dict={'a':1, 'b':2, 'c':3}
for key in some_dict:
    print(key)
print(some_dict['a'])

a
b
c
1


In [6]:
dict_iterator= iter(some_dict)
lItDict = list(dict_iterator)
print(lItDict)

['a', 'b', 'c']


## Checking out itertools

In [8]:
import itertools
#import functools

first_letter=lambda x:x[0]
names = ['Alan', 'Adam', 'Wes', 'Will', 'Albert', 'Steven']
for letter,names in itertools.groupby(names, first_letter):
    print(letter, list(names))


A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


In [ ]:
import numpy as np

arr1 = np.arange(1000000)
list1 =list(arr1)
print(arr1)
print(type(arr1))
print(list1)
print(type(list1))


In [24]:
np.random.seed(0)
data = np.random.randn(2,3)
print(data)

print(data*10)
data2 = data+data
print(data2)

print(data.shape)
print(data.dtype)

data3 = np.random.randn(2,3)
print(data3)

data4= [9,17.5, 12, 0, 0.5]
arr1 = np.array(data4)
print(arr1)

data5 = [[1,2,3,4], [5,6,7,8]]
arr2 = np.array(data5)
print(arr2)
print(arr2.dtype)
print(type(arr2))

np.zeros(10)
print(np.zeros((3,6)))

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]]
[[17.64052346  4.00157208  9.78737984]
 [22.40893199 18.6755799  -9.7727788 ]]
[[ 3.52810469  0.80031442  1.95747597]
 [ 4.4817864   3.73511598 -1.95455576]]
(2, 3)
float64
[[ 0.95008842 -0.15135721 -0.10321885]
 [ 0.4105985   0.14404357  1.45427351]]
[ 9.  17.5 12.   0.   0.5]
[[1 2 3 4]
 [5 6 7 8]]
int32
<class 'numpy.ndarray'>
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
